### ISSUE TITLE
最新版从什么位置配置AI？

### ISSUE THREAD

**Issue by epony4c** [sule01u/AutorizePro#11]
RT
![微信图片_20241226161016](https://github.com/user-attachments/assets/53bf0290-36e2-4ba5-8cdc-b9da974b3fc7)

**Comment by sule01u** [comment]
> RT ![微信图片_20241226161016](https://private-user-images.githubusercontent.com/17228839/398676890-53bf0290-36e2-4ba5-8cdc-b9da974b3fc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjQ3MjEsIm5iZiI6MTczNTI2NDQyMSwicGF0aCI6Ii8xNzIyODgzOS8zOTg2NzY4OTAtNTNiZjAyOTAtMzZlMi00YmE1LThjZGMtYjlkYTk3NGIzZmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDAxNTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkOWYxODhkNGNjMmI4N2IwMTVlMzI5YzUzYzQ3NzZhMGQxYTRmYThhOGZlZGEwYTM5NjIzNDVjYjY3YjMwNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yI7D8LHeZINLM1v_iymNsl-g2iznz_wyBI_CyRnJQ8M)

![image](https://github.com/user-attachments/assets/ec592083-7ebb-4654-a9a3-4ac86c97bc8c)

这位师傅你串台了，我的插件叫AutorizePro

从这里下载最新版本后按照readme进行安装：https://github.com/sule01u/AutorizePro/releases/tag/v1.4
