### ISSUE TITLE
阿里AI需要开通哪一个模型的授权？

### ISSUE THREAD

**Issue by amoy6228** [sule01u/AutorizePro#3]
如何查看API是否配置成功？
是否需要开通特定模型API的授权？
![image](https://github.com/user-attachments/assets/84f85c30-3f26-4f51-becd-ea9230cd2eb5)

**Comment by sule01u** [comment]
Q：是否需要开通特定模型API的授权
A：开通即可使用所有模型哦，工具中默认使用qwen-turbo；

Q：如何查看API是否配置成功？
A:   勾选API-KEY, 填写sk，然后点击AutorizePro is off 按钮启用插件，这时候burp代理的请求，你这边应该能看到AI列已经有分析结果了。
B: 如果没看到结果，可以在插件安装的地方查看是否有error日志
![image](https://github.com/user-attachments/assets/07b31028-dd9d-48a8-90ae-62f38bc7e6c6)
