### ISSUE TITLE
Configuration界面的上下分界处拖不动

### ISSUE THREAD

**Issue by L1j1aj0n** [sule01u/AutorizePro#6]
Configuration界面的上下分界处拖不动，字体设置为14号时候就看不见fetch cookie header选项了

**Comment by sule01u** [comment]
非常感谢反馈！预计周日更新

**Comment by L1j1aj0n** [comment]
好耶

**Comment by sule01u** [comment]
已更新，现在可以任意调节上下面板的占比（你可以通过下载最新的v1.2版本使用最新的一些功能吧）
